spring:
  session:
    store-type: none

security:
  basic:
    enabled: false

customer:
  security:
    code:
      image:
        width: 85
        height: 36
        length: 6
        expireIn: 60
    browser:
      loginPage: /demo-login.html
